#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()
env.Append(CCFLAGS = '-std=c++11 -Wno-deprecated-declarations')

liborigin_vn = env.Library('origin_vn', ['origin_vn.cc'])

originvn_test_cases = env.SConscript('test/SConscript', exports='BuildEnv',
                                     duplicate = 0)
Return('originvn_test_cases')
