#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')

env = BuildEnv.Clone()
env.Append(CCFLAGS = '-std=c++11 -Wno-deprecated-declarations')

librtarget = env.Library('security_group', ['security_group.cc'])
