#
# Copyright (c) 2014 CodiLime, Inc. All rights reserved.
#

# -*- mode: python; -*-

Import('BuildEnv')
import sys
env = BuildEnv.Clone()

env.Append(LIBPATH = env['TOP'] + '/base')
env.Append(LIBPATH = env['TOP'] + '/io')

source = ['bfd_state_machine.cc', 'bfd_control_packet.cc', 'bfd_session.cc',
          'bfd_server.cc', 'bfd_udp_connection.cc', 'bfd_common.cc']
libbfd = env.Library('bfd', source)

env.SConscript('test/SConscript', exports='BuildEnv', duplicate = 0)
env.SConscript('rest_api/SConscript', exports='BuildEnv', duplicate = 0)

env.Prepend(LIBS = ['io', 'base', 'bfd', 'gunit', 'io', 'sandesh',
                    'sandeshvns', 'process_info', 'base', 'http', 'io',
                    'ssl', 'crypto', 'http_parser', 'curl', 'pugixml',
                    'boost_program_options', 'boost_thread', 'boost_chrono'])
contrail_bfd = env.Program(target = 'contrail-bfd', source = ['main.cc'])
env.Alias('contrail-bfd', contrail_bfd)
